# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filename',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
